import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import { HomePage } from '@/src/components/home/home-page'
import { Footer } from '@/src/components/footer/footer'
import { Header } from '@/src/components/header/header'
export default function Home({data}) {
  return (
    <>
    <div >
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <HomePage data={data}></HomePage>
     
      
      </div>
    </>
  )
}
export async function getServerSideProps(){
  const {events_categories}=await import('/data/data.json');
  //console.log(events_categories);
  
  return {
    props:{
      data:events_categories,
    }
  }
}